### ISSUE TITLE
W’ Bal Details - Any Chance?

### ISSUE THREAD

**Issue by GuiPerPT** [ruffk/ZwiftActivityMonitor#4]
Hi, first of all, great work! A really powerful tool for Zwift.

Any chance you add details on the W’ Bal? This is a really useful metric, which tells you how much "energy" you still have available for anaerobic efforts. Further details here https://www.trinakan.com/wp/2016/04/02/everything-about-my-w-bal-w-prime-balance-connect-iq-app/ 

If I could see my energy balance before taking the decision of giving up and get dropped could help me take a wiser decision every time. 

Thanks in advance!

**Comment by ruffk** [comment]
So glad you're enjoying ZAM!

I've heard of this metric before and I'm just not convinced that it's really any more telling than looking at your intensity factor over a period of riding.  Reviewing the link you sent, even some of the comments to the creator of the widget seem to echo my sentiment.

I'm not saying it won't ever be implemented, but I've got some other high priority features to get started on.

Thanks again!

**Comment by GuiPerPT** [comment]
Thanks for the reply! 

Got it! Just want to add that the metric is different, as it reflects how much "energy" you have at a given moment of your activity, moving up or down if you are doing effort under or above CP, not the overall intensity of the effort as the IF. 

A good example, when I got dropped from the front group in a ZRL race 2 weeks ago, my W"Bal was down to the value of 3.4. I felt empty when I got dropped, but apparently could (in theory, as each day is different, but...) push it a little bit longer. Would I keep going if I kwow the "energy" value? Maybe... 
![Screen Shot 2021-04-30 at 10 00 21 AM](https://user-images.githubusercontent.com/478773/116666202-fc6d2080-a99a-11eb-8236-142ac26ba457.png)
 
Another example from the TTT on box hill some weeks ago. Clearly, a breakthrough, as I got to the negatives (don't remember the second part of the hill, but I GAVE EVERYTHING I had to keep up with the team). Maybe if I would see the value so low I would drop, but on the other side, you can see you are doing a breakthrough.  

![Screen Shot 2021-04-30 at 10 03 22 AM](https://user-images.githubusercontent.com/478773/116666616-743b4b00-a99b-11eb-9c0c-055a32e24b85.png)

Anyway, I respect your decision, and might consider forking and implement it myself doing a PR later on :) 

Keep up the good work!
