### ISSUE TITLE
Percentage Values

### ISSUE THREAD

**Issue by icemarkom** [ruffk/ZwiftActivityMonitor#6]
First of all, what a wonderful idea -- sandbaggers dream app! :-)

Any chance the weighted average can be configured to display a predefined/configurable percentage of the average power, as well? Specifically, 95% of 20 minute :-)

**Comment by ruffk** [comment]
Hi. Any collector can be enabled to show FTP, which is 95% of the Avg (Max) value. By default the 20 minute collector has this enabled. Hope this helps. Also, please join the Zwift Activity Monitor Users group on FB.

**Comment by icemarkom** [comment]
Ah, indeed, that's a valid point. Not immediately obvious, since I associate FTP with a fixed value, unless I am actually doing the test to determine it. Thanks.
