### ISSUE TITLE
60' FTP Formula

### ISSUE THREAD

**Issue by Helioth** [ruffk/ZwiftActivityMonitor#7]
60 minutes FTP applies the 0.95 factor on average value. While this is ok for the 20 minutes FTP, it should be 1.0 for the 60 minutes FTP. Didn't test other time intervals though.
![Untitled2](https://user-images.githubusercontent.com/2826215/118389816-085c1200-b62c-11eb-8bf1-73ba28390180.png)

**Comment by Helioth** [comment]
We’ve had a discussion on FB about renaming the column “FTP” to “95%” because it could be inaccurate if the testing protocol wasn’t precisely followed. These proxys are however widely used by most in a number of situations.

I would therefore however suggest either a new custom power column where anyone is able to enter a fraction of the power (using the usual right click). For example, 0.95 * Watts for the 20 minutes power, 1 * Watts for the 60 minutes, etc.

Or, better, a new column “Est. FTP” (so that nobody gets confused...) with predefined values: 0.95 for 20’, 1.0 for 60’ and above, 0.85 for 5’ and 0 below (5’ is already testing the maximal anareobic power rather than FTP so it is a bit tricky to use that one, but as a rough proxy some research shows it is about 85%), and a linear interpolation for other intervals, i.e. 0.8566 for 6’, 0.8833 for 10’, 0.9625 for 30’.

The current “95%” column is pretty much useless because the only relevant interval is 20’.

**Comment by ruffk** [comment]
Closing issue as this is more of a feature request...and only one user is asking for it.
